language: node_js
node_js:
  - stable

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install
script:
  - yarn test

deploy:
  provider: npm
  email: qas612820704@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
